export const FETCH_ACTIVITIES = 'FETCH_ACTIVITIES';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';
export const UPDATE_ACTIVITY_IN_PROGRESS = 'UPDATE_ACTIVITY_IN_PROGRESS';
export const ACTIVITY_UPDATED = 'ACTIVITY_UPDATED';
